### PR TITLE
Use a map for the cache

### PR DESCRIPTION
**Pull request by mathiasbynens**
Ref. #5.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Hah, the build failures seem unrelated to the patch. https://travis-ci.org/hzoo/babel-plugin-dedupe-string-literals/jobs/132474393#L225

**Comment by hzoo** [comment]
Yeah I have to merge the changes from before b/c I added travis and https://github.com/thejameskyle/generator-babel-plugin/pull/7 didn't include the packages for npm 2

**Comment by hzoo** [comment]
I merged the string change so there's a merge conflict.

If you want, you can remove 0.10 from travis and then add node engines >= 0.12 and we can make this a breaking change?

**Comment by mathiasbynens** [comment]
Rebased + removed `0.10`.

**Comment by hzoo** [comment]
btw, I can add you as a collab as well?

**Comment by hzoo** [comment]
K published 2.0.0

**Pull request merged**
